name: Upload metadata.yaml to S3

on:
  push:
    branches:
      - main

jobs:
  upload-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload metadata.yaml
        run: |
          aws s3 cp metadata.yaml s3://mfe-metadata-448388552206-us-east-1/metadata-$(date +%s).yaml
